Repository WalletConnect/WalletConnectSwiftV2, pull requests merged in 2022-08, with the labels that each got.

#388 feat: moves issues to the Swift board
  .github/workflows/intake.yml
Labels: accepted

#384 [Network] Refactor: #355 Relay client RPC
  Package.swift
  Sources/Commons/Either.swift
  Sources/JSONRPC/RPCRequest.swift
  Sources/JSONRPC/RPCResponse.swift
  Sources/WalletConnectRelay/RPC/Methods.swift
  Sources/WalletConnectRelay/RPC/RPCMethod.swift
  Sources/WalletConnectRelay/RPC/RelayRPC.swift
  Sources/WalletConnectRelay/RPC/WalletConnectRPCID.swift
  Sources/WalletConnectRelay/RelayClient.swift
  Sources/WalletConnectRelay/RelayJSONRPC.swift
  Sources/WalletConnectSign/NetworkInteractor/NetworkRelaying.swift
  Sources/WalletConnectUtils/Encodable.swift
  Sources/WalletConnectUtils/RPCHistory.swift
  Tests/RelayerTests/IridiumRelayTests.swift
  Tests/RelayerTests/Mocks/DispatcherMock.swift
  Tests/RelayerTests/RelayClientTests.swift
  Tests/TestingUtils/Mocks/RPC.swift
  Tests/WalletConnectKMSTests/KeychainStorageTests.swift
  Tests/WalletConnectSignTests/Mocks/MockedRelayClient.swift
  Tests/WalletConnectUtilsTests/RPCHistoryTests.swift
Labels: enhancement

#392 feat: only run ui test on release
  .github/workflows/ci.yml
Labels: accepted

#402 [Network] #364: Change relay methods prefix from "iridium" to "irn"
  Sources/WalletConnectPairing/Types/WCPairing.swift
  Sources/WalletConnectRelay/RPC/RelayRPC.swift
  Sources/WalletConnectRelay/RelayClient.swift
  Tests/WalletConnectSignTests/Stub/Stubs.swift
  Tests/WalletConnectSignTests/WCRelayTests.swift
  Tests/WalletConnectSignTests/WalletConnectURITests.swift
Labels: protocol, accepted

#398 [Tests] #250 Session Request integration tests re-enabled
  Example/ExampleApp.xcodeproj/project.pbxproj
  Example/IntegrationTests/Sign/Helpers/ClientDelegate.swift
  Example/IntegrationTests/Sign/Helpers/EthSendTransaction.swift
  Example/IntegrationTests/Sign/SignClientTests.swift
  Example/IntegrationTests/Stubs/Stubs.swift
  Sources/WalletConnectSign/Request.swift
Labels: accepted

#397 [Auth] #395 Auth Request Subscriber
  Sources/Auth/Services/Common/NetworkingInteractor.swift
  Sources/Auth/Services/Common/SIWEMessageFormatter.swift
  Sources/Auth/Services/Wallet/AuthRequestSubscriber.swift
  Sources/Auth/Services/Wallet/AuthRespondService.swift
  Sources/Auth/Types/Cacao/CacaoHeader.swift
  Sources/Auth/Types/Cacao/CacaoPayload.swift
  Sources/Auth/Types/Cacao/CacaoSignature.swift
  Sources/Auth/Types/ProtocolRPCParams/AuthRequestParams.swift
  Sources/Auth/Types/ProtocolRPCParams/AuthResponseParams.swift
  Sources/Auth/Types/RequestSubscriptionPayload.swift
  Sources/JSONRPC/RPCID.swift
  Sources/JSONRPC/RPCRequest.swift
  Sources/JSONRPC/RPCResponse.swift
  Sources/WalletConnectRelay/RPC/WalletConnectRPCID.swift
  Tests/AuthTests/AuthClientTest.swift
  Tests/AuthTests/AuthRequstSubscriberTests.swift
  Tests/AuthTests/Mocks/NetworkingInteractorMock.swift
  Tests/AuthTests/Mocks/SIWEMessageFormatterMock.swift
  Tests/AuthTests/Stubs/RequestParams.swift
  Tests/AuthTests/Stubs/RequestSubscriptionPayload.swift
  Tests/TestingUtils/Mocks/RPC.swift
Labels: accepted

#401 [Auth] #377 Auth respond service
  Example/IntegrationTests/Chat/ChatTests.swift
  Package.swift
  Sources/Auth/Services/App/AuthRequestService.swift
  Sources/Auth/Services/Common/CacaoFormatter.swift
  Sources/Auth/Services/Common/NetworkingInteractor.swift
  Sources/Auth/Services/Wallet/AuthRequestSubscriber.swift
  Sources/Auth/Services/Wallet/AuthRespondService.swift
  Sources/Auth/Types/Cacao/Cacao.swift
  Sources/Auth/Types/ProtocolRPCParams/AuthRequestParams.swift
  Sources/Auth/Types/ProtocolRPCParams/AuthResponseParams.swift
  Sources/Auth/Types/RequestSubscriptionPayload.swift
  Sources/Auth/Types/RespondParams.swift
  Sources/Chat/ChatClientFactory.swift
  Sources/JSONRPC/RPCResponse.swift
  Sources/WalletConnectUtils/RPCHistory.swift
  Tests/AuthTests/Mocks/NetworkingInteractorMock.swift
  Tests/AuthTests/Mocks/SIWEMessageFormatterMock.swift
  Tests/AuthTests/Stubs/RequestSubscriptionPayload.swift
  Tests/WalletConnectSignTests/ApproveEngineTests.swift
Labels: accepted

#408 Version bump to v0.9.2-rc.0
  Sources/WalletConnectRelay/EnvironmentInfo.swift
Labels: accepted

#404 #396 auth respond subscriber
  Sources/Auth/Services/App/AuthRespondSubscriber.swift
  Sources/Auth/Services/Common/CacaoSignatureVerifier.swift
  Sources/Auth/Services/Common/NetworkingInteractor.swift
  Sources/Auth/Types/Cacao/Cacao.swift
  Sources/Auth/Types/RequestSubscriptionPayload.swift
  Sources/Auth/Types/ResponseSubscriptionPayload.swift
  Tests/AuthTests/Mocks/NetworkingInteractorMock.swift
Labels: accepted

#410 Fix unit test run
  .github/actions/ci/action.yml
  Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift
  Tests/AuthTests/Stubs/RequestSubscriptionPayload.swift
  Tests/JSONRPCTests/Helpers.swift
  Tests/JSONRPCTests/RPCRequestTests.swift
  Tests/JSONRPCTests/RPCResponseTests.swift
  Tests/TestingUtils/Helpers.swift
  Tests/WalletConnectSignTests/Mocks/NetworkingInteractorMock.swift
  Tests/WalletConnectSignTests/PairingEngineTests.swift
  Tests/WalletConnectUtilsTests/RPCHistoryTests.swift
Labels: accepted

#418 update user-agent
  Sources/WalletConnectRelay/EnvironmentInfo.swift
Labels: accepted

#412 v0.9.3-rc.0
  .github/actions/ci/action.yml
  Sources/Auth/Services/App/AuthRespondSubscriber.swift
  Sources/Auth/Services/Common/CacaoSignatureVerifier.swift
  Sources/Auth/Services/Common/NetworkingInteractor.swift
  Sources/Auth/Services/Common/SIWEMessageFormatter.swift
  Sources/Auth/Services/Wallet/AuthRequestSubscriber.swift
  Sources/Auth/Types/AuthPayload.swift
  Sources/Auth/Types/Cacao/Cacao.swift
  Sources/Auth/Types/RequestParams.swift
  Sources/Auth/Types/RequestSubscriptionPayload.swift
  Sources/Auth/Types/ResponseSubscriptionPayload.swift
  Sources/WalletConnectRelay/EnvironmentInfo.swift
  Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift
  Tests/AuthTests/AuthRequstSubscriberTests.swift
  Tests/AuthTests/Mocks/NetworkingInteractorMock.swift
  Tests/AuthTests/Mocks/SIWEMessageFormatterMock.swift
  Tests/AuthTests/SIWEMessageFormatterTests.swift
  Tests/AuthTests/Stubs/AuthPayload.swift
  Tests/AuthTests/Stubs/RequestParams.swift
  Tests/AuthTests/Stubs/RequestSubscriptionPayload.swift
  Tests/JSONRPCTests/Helpers.swift
  Tests/JSONRPCTests/RPCRequestTests.swift
  Tests/JSONRPCTests/RPCResponseTests.swift
  Tests/TestingUtils/Helpers.swift
  Tests/WalletConnectSignTests/Mocks/NetworkingInteractorMock.swift
  Tests/WalletConnectSignTests/PairingEngineTests.swift
  Tests/WalletConnectUtilsTests/RPCHistoryTests.swift
Labels: accepted

#419 [Sign] #372 Clean protocol codes
  Example/ExampleApp/Wallet/WalletViewController.swift
  Example/IntegrationTests/Sign/SignClientTests.swift
  Sources/Auth/Services/Common/SIWEMessageFormatter.swift
  Sources/Auth/Services/Wallet/AuthRequestSubscriber.swift
  Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift
  Sources/WalletConnectSign/Engine/Common/SessionEngine.swift
  Sources/WalletConnectSign/Engine/NonController/NonControllerSessionStateMachine.swift
  Sources/WalletConnectSign/RejectionReason.swift
  Sources/WalletConnectSign/Types/ReasonCode.swift
  Tests/AuthTests/SIWEMessageFormatterTests.swift
  Tests/WalletConnectSignTests/NonControllerSessionStateMachineTests.swift
Labels: accepted

#421 #382 auth networking interactor
  Example/IntegrationTests/Sign/SignClientTests.swift
  Sources/Auth/Services/App/AuthRequestService.swift
  Sources/Auth/Services/App/AuthRespondSubscriber.swift
  Sources/Auth/Services/Common/NetworkingInteractor.swift
  Sources/Auth/Services/Common/SIWEMessageFormatter.swift
  Sources/Auth/Services/Wallet/AuthRequestSubscriber.swift
  Sources/Auth/Types/ResponseSubscriptionPayload.swift
  Sources/WalletConnectSign/Engine/Common/ApproveEngine.swift
  Sources/WalletConnectUtils/RPCHistory.swift
  Tests/AuthTests/Mocks/NetworkingInteractorMock.swift
  Tests/AuthTests/SIWEMessageFormatterTests.swift
Labels: accepted

#407 fix: intake process does not work for non-public org members
  .github/workflows/intake.yml
Labels: accepted

#405 [Auth] Cacao signer
  .github/actions/ci/action.yml
  .github/workflows/ci.yml
  .swiftpm/xcode/xcshareddata/xcschemes/WalletConnectAuth.xcscheme
  Example/ExampleApp.xcodeproj/project.pbxproj
  Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Example/IntegrationTests/Chat/ChatTests.swift
  Package.swift
  Sources/Auth/Extensions/Data+Keccak256.swift
  Sources/Auth/Services/App/AppRespondSubscriber.swift
  Sources/Auth/Services/Common/CacaoSignatureVerifier.swift
  Sources/Auth/Services/Common/SIWEMessageFormatter.swift
  Sources/Auth/Services/Signer/DIDPKH.swift
  Sources/Auth/Services/Signer/MessageSigner.swift
  Sources/Auth/Services/Signer/Signer.swift
  Sources/Auth/Services/Wallet/WalletRequestSubscriber.swift
  Sources/Auth/Types/Cacao/CacaoPayload.swift
  Tests/AuthTests/CacaoSignerTests.swift
  Tests/AuthTests/Mocks/SIWEMessageFormatterMock.swift
  Tests/AuthTests/SignerTests.swift
Labels: accepted

#424 [Core] WalletConnectRouter
  Example/DApp/SelectChain/SelectChainView.swift
  Example/DApp/SelectChain/SelectChainViewController.swift
  Example/ExampleApp.xcodeproj/project.pbxproj
  Example/ExampleApp/Wallet/WalletViewController.swift
  Package.swift
  Sources/WalletConnectRouter/Router.m
  Sources/WalletConnectRouter/include/Router.h
  Sources/WalletConnectRouter/include/module.modulemap
Labels: accepted

#428 Create pull_request_template.md
  .github/pull_request_template.md
Labels: accepted

#436 [Hotfix] EIP-155 signature fix
  Example/ExampleApp.xcodeproj/project.pbxproj
  Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
  Sources/Auth/Services/Signer/Signer.swift
  Tests/AuthTests/CacaoSignerTests.swift
  Tests/AuthTests/SignerTests.swift
Labels: accepted

#438 [Relay] Relay Singleton instance
  Example/DApp/SceneDelegate.swift
  Example/ExampleApp.xcodeproj/project.pbxproj
  Example/ExampleApp/SceneDelegate.swift
  Example/ExampleApp/SessionDetails/SessionDetailViewController.swift
  Example/ExampleApp/SessionDetails/SessionDetailViewModel.swift
  Example/IntegrationTests/Relay/RelayClientEndToEndTests.swift
  Example/IntegrationTests/Sign/Helpers/ClientDelegate.swift
  Package.swift
  Sources/Auth/AuthClient.swift
  Sources/Auth/Services/Signer/MessageSigner.swift
  Sources/Auth/Services/Wallet/WalletRequestSubscriber.swift
  Sources/Chat/NetworkingInteractor.swift
  Sources/WalletConnectRelay/Relay.swift
  Sources/WalletConnectRelay/RelayClient.swift
  Sources/WalletConnectRelay/RelayConfig.swift
  Sources/WalletConnectSign/NetworkInteractor/NetworkInteractor.swift
  Sources/WalletConnectSign/NetworkInteractor/NetworkRelaying.swift
  Sources/WalletConnectSign/Sign/Sign.swift
  Sources/WalletConnectSign/Sign/SignClient.swift
  Sources/WalletConnectSign/Sign/SignClientDelegate.swift
  Sources/WalletConnectSign/Sign/SignConfig.swift
  Tests/RelayerTests/RelayClientTests.swift
  Tests/WalletConnectSignTests/Mocks/MockedRelayClient.swift
  Tests/WalletConnectSignTests/WCRelayTests.swift
Labels: accepted

#443 Develop main
  .github/pull_request_template.md
  Sources/Auth/Services/App/AppRequestService.swift
  Sources/Auth/Services/App/AppRespondSubscriber.swift
  Sources/Auth/Services/Common/NetworkingInteractor.swift
  Sources/Auth/Types/ResponseSubscriptionPayload.swift
  Sources/WalletConnectUtils/RPCHistory.swift
  Tests/AuthTests/Mocks/NetworkingInteractorMock.swift
Labels: accepted

#441 [Auth] #434 auth client factory
  Example/ExampleApp.xcodeproj/project.pbxproj
  Example/IntegrationTests/Auth/AuthTests.swift
  Package.swift
  Sources/Auth/AuthClient.swift
  Sources/Auth/AuthClientFactory.swift
  Sources/Auth/Services/Common/CleanupService.swift
  Sources/Auth/Services/Common/NetworkingInteractor.swift
  Sources/Auth/Services/Wallet/WalletRequestSubscriber.swift
  Sources/Auth/StorageDomainIdentifiers.swift
  Sources/Auth/Types/Aliases/Account.swift
  Sources/Auth/Types/RequestParams.swift
  Sources/Auth/Types/RespondParams.swift
  Sources/WalletConnectSign/Sign/SignClient.swift
Labels: accepted

#448 [Auth] #416 auth request test
  Example/ExampleApp.xcodeproj/project.pbxproj
  Example/IntegrationTests/Auth/AuthTests.swift
  Example/IntegrationTests/Stubs/RequestParams.swift
  Sources/Auth/AuthClientFactory.swift
  Sources/Auth/Services/App/AppRequestService.swift
  Sources/Auth/Services/App/AppRespondSubscriber.swift
  Sources/Auth/Services/Common/CacaoFormatter.swift
  Sources/Auth/Services/Common/NetworkingInteractor.swift
  Sources/Auth/Services/Wallet/WalletRequestSubscriber.swift
  Sources/Auth/Services/Wallet/WalletRespondService.swift
  Sources/Auth/Types/Cacao/CacaoPayload.swift
  Sources/Auth/Types/Cacao/CacaoSignature.swift
  Sources/Auth/Types/ProtocolRPCParams/AuthRequestParams.swift
  Sources/Auth/Types/ProtocolRPCParams/AuthResponseParams.swift
  Sources/Auth/Types/RespondParams.swift
Labels: accepted

#449 [Auth] Handle errors
  Example/IntegrationTests/Auth/AuthTests.swift
  Sources/Auth/AuthClient.swift
  Sources/Auth/AuthClientFactory.swift
  Sources/Auth/Services/App/AppRespondSubscriber.swift
  Sources/Auth/Services/Common/NetworkingInteractor.swift
  Sources/Auth/Services/Wallet/WalletRequestSubscriber.swift
  Sources/Auth/Services/Wallet/WalletRespondService.swift
  Sources/Auth/Types/Cacao/CacaoSignature.swift
  Sources/Auth/Types/ErrorCode.swift
  Sources/Auth/Types/Errors/AuthError.swift
  Sources/Auth/Types/Errors/Reason.swift
  Sources/JSONRPC/RPCResponse.swift
  Tests/AuthTests/AuthRequstSubscriberTests.swift
  Tests/AuthTests/Mocks/NetworkingInteractorMock.swift
Labels: accepted

#457 [Auth] #453 invalid signature error
  Example/IntegrationTests/Auth/AuthTests.swift
  Sources/Auth/Services/App/AppRespondSubscriber.swift
  Sources/Auth/Services/Signer/MessageSigner.swift
  Sources/Auth/Services/Signer/Signer.swift
  Sources/Auth/Types/Cacao/CacaoSignature.swift
  Sources/Auth/Types/Errors/AuthError.swift
  Sources/Auth/Types/RespondParams.swift
Labels: accepted

#458 [Relay] Add invalidation of background task
  Sources/WalletConnectRelay/SocketConnectionHandler/AutomaticSocketConnectionHandler.swift
  Sources/WalletConnectRelay/SocketConnectionHandler/BackgroundTaskRegistering.swift
  Tests/RelayerTests/Mocks/BackgroundTaskRegistrarMock.swift
Labels: accepted

#455 #454 Update `WalletConnectURI` with API identifier prefix
  Sources/WalletConnectUtils/WalletConnectURI.swift
  Tests/WalletConnectSignTests/WalletConnectURITests.swift
  Tests/WalletConnectUtilsTests/WalletConnectURITests.swift
Labels: accepted

#468 0.10.1
  Sources/WalletConnectRelay/SocketConnectionHandler/AutomaticSocketConnectionHandler.swift
  Sources/WalletConnectRelay/SocketConnectionHandler/BackgroundTaskRegistering.swift
  Tests/AuthTests/AppRespondSubscriberTests.swift
  Tests/AuthTests/Mocks/AppMetadata.swift
  Tests/AuthTests/Mocks/NetworkingInteractorMock.swift
  Tests/AuthTests/Stubs/AuthPayload.swift
  Tests/AuthTests/Stubs/AuthRequestParams.swift
  Tests/AuthTests/WalletRequestSubscriberTests.swift
  Tests/WalletConnectSignTests/Mocks/AppMetadata.swift
  Tests/WalletConnectSignTests/Stub/Stubs.swift
Labels: accepted

#470 [Auth] Sample Wallet scan
  Example/DApp/Auth/AuthView.swift
  Example/DApp/Auth/AuthViewModel.swift
  Example/ExampleApp.xcodeproj/project.pbxproj
  Example/Showcase/Classes/ApplicationLayer/SceneDelegate.swift
  Example/Showcase/Classes/PresentationLayer/Wallet/Scan/ScanInteractor.swift
  Example/Showcase/Classes/PresentationLayer/Wallet/Scan/ScanModule.swift
  Example/Showcase/Classes/PresentationLayer/Wallet/Scan/ScanPresenter.swift
  Example/Showcase/Classes/PresentationLayer/Wallet/Scan/ScanRouter.swift
  Example/Showcase/Classes/PresentationLayer/Wallet/Scan/ScanView.swift
  Example/Showcase/Classes/PresentationLayer/Wallet/Scan/Views/ScanQR.swift
  Example/Showcase/Classes/PresentationLayer/Wallet/Scan/Views/ScanQRView.swift
  Example/Showcase/Classes/PresentationLayer/Wallet/Scan/Views/ScanTargetView.swift
  Example/Showcase/Classes/PresentationLayer/Wallet/Wallet/WalletPresenter.swift
  Example/Showcase/Classes/PresentationLayer/Wallet/Wallet/WalletRouter.swift
  Example/Showcase/Other/Info.plist
  Sources/Auth/AuthClient.swift
  Sources/WalletConnectRelay/AppStateObserving.swift
  Sources/WalletConnectRelay/SocketConnectionHandler/AutomaticSocketConnectionHandler.swift
Labels: accepted

#473 [API] Update public api docs
  Example/DApp/Sign/Connect/ConnectViewController.swift
  Example/IntegrationTests/Sign/SignClientTests.swift
  Sources/Auth/Auth.swift
  Sources/Auth/AuthClient.swift
  Sources/Auth/Types/Cacao/Cacao.swift
  Sources/Auth/Types/Errors/AuthError.swift
  Sources/Auth/Types/RequestParams.swift
  Sources/WalletConnectRelay/Relay.swift
  Sources/WalletConnectRelay/RelayClient.swift
  Sources/WalletConnectSign/Engine/Common/PairingEngine.swift
  Sources/WalletConnectSign/Sign/Sign.swift
  Sources/WalletConnectSign/Sign/SignClient.swift
Labels: accepted
